spring:
  #--------------------------charset--------------------------
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  servlet:
    multipart:
      max-file-size : 100MB
      max-request-size: 100MB

#--------------------------Server--------------------------
server:
  tomcat:
    uri-encoding: UTF-8
